runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "wine-quality-predictor-381604-86e6fc8b76b7.json"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
